name: 'Show new modules'
description: 'Show any new modules'
inputs:
  branch:  # branch to track modules for
    description: 'Branch'
    required: true
    default: 'master'
runs:
  using: 'composite'
  steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        path: repo
    - name: list files
      run: ls -R repo/**/**.pm repo/**/**.pl
      shell: bash
    - run: ls -R repo/**/**.pm repo/**/**.pl | ${{github.action_path}}/find_use.pl | sort | uniq > before.lst
      shell: bash
    - run: cat before.lst
      shell: bash
    - run: git checkout ${{github.ref}}
      shell: bash
    - run: ls -R repo/**/**.pm repo/**/**.pl | ${{github.action_path}}/find_use.pl | sort | uniq > after.lst
      shell: bash
    - run: cat after.lst
      shell: bash
    - id: diff
      run: diff before.lst after.lst
      shell: bash
