name: 'Show new modules'
description: 'Show any new modules'
inputs:
  branch:  # branch to track modules for
    description: 'Branch'
    required: true
    default: 'master'
outputs:
  new-modules: # id of output
    value: '${{ github.ref }}'
    description: 'The new modules that are used'
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v2
    - run: ls -R /secure/**/**.pm ~/Code/secure/**/**.pl | ${{github.action_path}}/find_use.pl | sort | uniq
      shell: bash
