name: 'Show new modules'
description: 'Show any new modules'
inputs:
  branch:  # branch to track modules for
    description: 'Branch'
    required: true
    default: 'master'
runs:
  using: 'composite'
  steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ inputs.branch }}
        path: secure
    - run: ls -R secure/**/**.pm secure/**/**.pl | ${{github.action_path}}/find_use.pl | sort | uniq > before.lst
      shell: bash
    - name: checkout
      uses: actions/checkout@v2
      with:
        path: compare
        ref: ${{ github.ref }}
    - run: ls -R compare/**/**.pm compare/**/**.pl | ${{github.action_path}}/find_use.pl | sort | uniq > after.lst
      shell: bash
    - id: diff
      run: diff before.lst after.lst
      shell: bash
